name: Docker image push

on:
  push:
    branches:    
    - main 
  schedule:
    - cron:  '0 0 * * 4'

jobs:
  docker_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distributions: [
          { "dist": "debian", "code_name": "buster", "image_name_suffix": "-slim", "ubuntu_code_name": "bionic", "node": 12 },
          { "dist": "ubuntu", "code_name": "bionic", "image_name_suffix": "", "ubuntu_code_name": "bionic", "node": 12 },
          { "dist": "debian", "code_name": "buster", "image_name_suffix": "-slim", "ubuntu_code_name": "bionic", "node": 14 },
          { "dist": "ubuntu", "code_name": "bionic", "image_name_suffix": "", "ubuntu_code_name": "bionic", "node": 14 },
          { "dist": "debian", "code_name": "buster", "image_name_suffix": "-slim", "ubuntu_code_name": "bionic", "node": 16 },
          { "dist": "ubuntu", "code_name": "bionic", "image_name_suffix": "", "ubuntu_code_name": "bionic", "node": 16 }
        ]
    steps:
    - uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
    - name: Build release
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}:node${{ matrix.distributions.node }}"
      run: |
        docker build --rm \
            -t "${IMAGE_TAG}" \
            --build-arg DEBIAN_DIST_NAME="${{ matrix.distributions.dist }}" \
            --build-arg DEBIAN_VERSION_NAME="${{ matrix.distributions.code_name }}" \
            --build-arg SLIM_IMAGE_SUFFIX="${{ matrix.distributions.image_name_suffix }}" \
            --build-arg UBUNTU_VERSION_NAME="${{ matrix.distributions.ubuntu_code_name }}" \
            --target=release \
            .
    - name: Build debug
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}-debug:node${{ matrix.distributions.node }}"
      run: |
        docker build --rm \
            -t "${IMAGE_TAG}" \
            --build-arg DEBIAN_DIST_NAME="${{ matrix.distributions.dist }}" \
            --build-arg DEBIAN_VERSION_NAME="${{ matrix.distributions.code_name }}" \
            --build-arg SLIM_IMAGE_SUFFIX="${{ matrix.distributions.image_name_suffix }}" \
            --build-arg UBUNTU_VERSION_NAME="${{ matrix.distributions.ubuntu_code_name }}" \
            .
    - name: push
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
        RELEASE_IMAGE: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}:node${{ matrix.distributions.node }}"
        DEBUG_IMAGE: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}-debug:node${{ matrix.distributions.node }}"
      run: |
        echo "${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}" | docker login https://docker.pkg.github.com -u poad --password-stdin && \
        docker push "${RELEASE_IMAGE}" && \
        docker push "${DEBUG_IMAGE}"

