name: Docker image push

on:
  push:
    branches:    
    - main 
  schedule:
    - cron:  '0 0 * * 4'

  # Try enabling auto-merge for the specified pull request or all open pull requests if none is specified.
  workflow_dispatch:

jobs:
  docker_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distributions: [
          { "dist": "ubuntu", "code_name": "jammy", "image_name_suffix": "", "ubuntu_code_name": "jammy", "node": 16 }
          # { "dist": "ubuntu", "code_name": "jammy", "image_name_suffix": "", "ubuntu_code_name": "jammy", "node": 18 },
          # { "dist": "ubuntu", "code_name": "jammy", "image_name_suffix": "", "ubuntu_code_name": "jammy", "node": 20 }
        ]
    steps:
    - uses: actions/checkout@v3
      if: github.event_name != 'pull_request'
    - name: Build release
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}:node${{ matrix.distributions.node }}"
      run: |
        docker build --rm \
            -t "${IMAGE_TAG}" \
            --build-arg DEBIAN_DIST_NAME="${{ matrix.distributions.dist }}" \
            --build-arg DEBIAN_VERSION_NAME="${{ matrix.distributions.code_name }}" \
            --build-arg SLIM_IMAGE_SUFFIX="${{ matrix.distributions.image_name_suffix }}" \
            --build-arg UBUNTU_VERSION_NAME="${{ matrix.distributions.ubuntu_code_name }}" \
            --build-arg NODE_VERSION="${{ matrix.distributions.node }}" \
            --target=release \
            .
    - name: Build debug
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}-debug:node${{ matrix.distributions.node }}"
      run: |
        docker build --rm \
            -t "${IMAGE_TAG}" \
            --build-arg DEBIAN_DIST_NAME="${{ matrix.distributions.dist }}" \
            --build-arg DEBIAN_VERSION_NAME="${{ matrix.distributions.code_name }}" \
            --build-arg SLIM_IMAGE_SUFFIX="${{ matrix.distributions.image_name_suffix }}" \
            --build-arg UBUNTU_VERSION_NAME="${{ matrix.distributions.ubuntu_code_name }}" \
            --build-arg NODE_VERSION="${{ matrix.distributions.node }}" \
            .
    - name: push
      if: github.event_name != 'pull_request'
      env:
        DOCKER_BUILDKIT: 1
        RELEASE_IMAGE: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}:node${{ matrix.distributions.node }}"
        DEBUG_IMAGE: "ghcr.io/poad/docker-aws-lambda-container-images/${{ matrix.distributions.dist }}-debug:node${{ matrix.distributions.node }}"
      run: |
        echo "${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}" | docker login ghcr.io -u poad --password-stdin && \
        docker push "${RELEASE_IMAGE}" && \
        docker push "${DEBUG_IMAGE}"

