name: Docker image build

on:
  pull_request:
    branches:
      - main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distributions: [
          { "dist": "debian", "code_name": "buster", "image_name_suffix": "-slim", "ubuntu_code_name": "bionic", "node": 12 },
          { "dist": "ubuntu", "code_name": "bionic", "image_name_suffix": "", "ubuntu_code_name": "bionic", "node": 12 },
          { "dist": "debian", "code_name": "buster", "image_name_suffix": "-slim", "ubuntu_code_name": "bionic", "node": 14 },
          { "dist": "ubuntu", "code_name": "bionic", "image_name_suffix": "", "ubuntu_code_name": "bionic", "node": 14 },
          { "dist": "debian", "code_name": "buster", "image_name_suffix": "-slim", "ubuntu_code_name": "bionic", "node": 16 },
          { "dist": "ubuntu", "code_name": "bionic", "image_name_suffix": "", "ubuntu_code_name": "bionic", "node": 16 }
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ matrix.distributions.dist }} ${{ matrix.distributions.code_name }} with Node.js ${{ matrix.distributions.node }}
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build --rm \
            -t "${{ matrix.distributions.dist }}:node${{ matrix.distributions.node }}" \
            --build-arg DEBIAN_DIST_NAME="${{ matrix.distributions.dist }}" \
            --build-arg DEBIAN_VERSION_NAME="${{ matrix.distributions.code_name }}" \
            --build-arg SLIM_IMAGE_SUFFIX="${{ matrix.distributions.image_name_suffix }}" \
            --build-arg UBUNTU_VERSION_NAME="${{ matrix.distributions.ubuntu_code_name }}" \
            .
    - name: Hadolint
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile
    
    - name: Test
      run: |
        cd tests
        docker build --rm \
            --build-arg IMAGE_TAG="${{ matrix.distributions.dist }}:node${{ matrix.distributions.node }}" \
            -t lambda:latest \
            .
        docker run -p 9000:8080 --name lambda -d lambda:latest
        curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
